### ISSUE TITLE
its fake

### ISSUE THREAD

**Issue by klgor1803** [XKMR/DDoS-attack-tool#1]
besides having unnecessary texts, the code does not even send 1 byte to the inserted ip, XKMR made a [comment](https://github.com/Ha3MrX/DDos-Attack/issues/62#issue-1007016769) saying the Ha3Mrx code is fake, while the XKMR code is fake, man, I don't know what's in your head, but I have a hunch: poop

**Comment by XKMR** [comment]
bro normal people just must not have access to these dangerous tools. so I just faked it to let them be happy with this.
